#ifndef CONSTANTS_H
#define CONSTANTS_H

#define ROLE_PASSIVE 1
#define ROLE_CANDIDATE 2
#define ROLE_SEARCHER 3
#define ROLE_BASEKEEPER 4

#define MESSAGETYPE_CAPTUREBROADCAST 0x01
#define MESSAGETYPE_CAPTUREACK 0x02
#define MESSAGETYPE_CANDIDATEKILLED 0x03
#define MESSAGETYPE_SHAREPOSITION 0x04
#define MESSAGETYPE_RECRUITNEWBASEKEEPER 0x05
#define MESSAGETYPE_PINGALLBASEKEEPERS 0x06
#define MESSAGETYPE_PINGREPLY 0x07
#define MESSAGETYPE_APPLYASBASEKEEPER 0x08
#define MESSAGETYPE_APPOINTNEWBASEKEEPER 0x09
#define MESSAGETYPE_HEARTBEAT 0x0a
#define MESSAGETYPE_BECOMEBASEKEEPER 0x0b
#define MESSAGETYPE_RELOCATESEARCHER 0x0c
#define MESSATETYPE_BASEKEEPERUPDATE 0x0d
#define MESSAGETYPE_DISBAND 0x0e
#define MESSAGETYPE_FOUNDTARGET 0x0f
// #define MESSAGETYPE_NOTIFYTOTALSEARCHERS 0x10
#define MESSAGETYPE_FOUNDTARGETUPSTREAM 0x11
#define MESSAGETYPE_PATHDATA 0x12
#define MESSAGETYPE_BECOMEPATHPOINT 0x13

#endif